### ISSUE TITLE
Bad RefreshAuthTokenAsync call

### ISSUE THREAD

**Issue by TalicZealot** [swiftyspiffy/Twitch-Auth-Example#1]
At
 https://github.com/swiftyspiffy/Twitch-Auth-Example/blob/4fa7b507433e803bd0b9c4e02055fb61ead49761/TwitchAuthExample/Program.cs#L49
 RefreshAuthTokenAsync  should take a refresh token from the original response, not the access token.

**Comment by swiftyspiffy** [comment]
Fixed here: https://github.com/swiftyspiffy/Twitch-Auth-Example/commit/2b516d1e5cd123f173a1b79f1f743ef2d25a2374

Thanks for bringing this up :)
